import os

SEASON_ID = 48  # 2019 Fall
GOOGLE_EMAIL = os.getenv('GOOGLE_EMAIL')
GOOGLE_PASSWORD = os.getenv('GOOGLE_PASSWORD')
HXEB_DB_HOST = os.getenv('HXEB_DB_HOST')
HXEB_DB_USER = os.getenv('HXEB_DB_USER')
HXEB_DB_PASSWORD = os.getenv('HXEB_DB_PASSWORD')
HXEB_DB_NAME = os.getenv('HXEB_DB_NAME')
